FROM node:22-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY front/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY front .

# Exposer le port
EXPOSE 5173

# Lancer le serveur de développement
CMD ["npm", "run", "dev"]
