name: Rust CI

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master"]

jobs:
  check_and_build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Build
        run: cargo build --verbose

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings
