input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] {
    mutate {
      add_field => { "service_name" => "%{[container][name]}" }
    }
  }

  mutate {
    gsub => [ "service_name", "^/", "" ]
  }

  json {
    source => "message"
    target => "docker_log"
  }

  if [docker_log][log] {
    mutate {
      replace => { "message" => "%{[docker_log][log]}" }
    }
    mutate {
      gsub => [ "message", "\x1b\[[0-9;]*m", "" ]
    }
  }

  if ![level] {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:log_timestamp}\s+%{LOGLEVEL:level}\s+%{GREEDYDATA:log_message}" }
      tag_on_failure => ["_grokparsefailure_generic"]
    }
  }

  mutate {
    remove_field => ["agent", "ecs", "input", "log", "host", "docker_log"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "logstash_internal"
    password => "${LOGSTASH_PASSWORD}"
    index => "ft_transcendence-logs-%{+YYYY.MM.dd}"
  }
}
