export const styles = {
  page: {
    maxWidth: "40rem",
    margin: "0 auto",
    padding: "1.5rem",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2rem",
    color: "#fff",
    background: "#111",
    minHeight: "100vh",
  },
  section: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.5rem",
    borderBottom: "0.0625rem solid #333",
    paddingBottom: "1rem",
  },
  label: {
    fontSize: "0.9rem",
    color: "#aaa",
  },
  input: {
    padding: "0.5rem",
    fontSize: "1rem",
    borderRadius: "0.25rem",
    border: "0.0625rem solid #444",
    background: "#1a1a1a",
    color: "#fff",
  },
  button: {
    padding: "0.5rem 1rem",
    fontSize: "1rem",
    borderRadius: "0.25rem",
    border: "none",
    cursor: "pointer",
    background: "#2b6",
    color: "#fff",
    width: "fit-content",
  },
  dangerButton: {
    padding: "0.5rem 1rem",
    fontSize: "1rem",
    borderRadius: "0.25rem",
    border: "0.0625rem solid #c33",
    cursor: "pointer",
    background: "transparent",
    color: "#f66",
    width: "fit-content",
  },
  row: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
  },
};