{
 "title": "Router Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Router Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "router_requests_total{route!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_requests_total{route!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(router_errors_total[5m])) / sum(rate(router_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Http Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Router Latency p50/p95/p98/p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(max(router_latency_p50_ms{route!=\"\"}), \"percentile\", \"p50\", \"\", \"\") or\nlabel_replace(max(router_latency_p95_ms{route!=\"\"}), \"percentile\", \"p95\", \"\", \"\") or\nlabel_replace(max(router_latency_p98_ms{route!=\"\"}), \"percentile\", \"p98\", \"\", \"\") or\nlabel_replace(max(router_latency_p99_ms{route!=\"\"}), \"percentile\", \"p99\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}