apiVersion: 1
groups:
  - orgId: 1
    name: system-alerts
    folder: ft-transcendence
    interval: 1m
    rules:
      - uid: cfulje7j4eebke
        title: CPU high usage
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: >-
                (100 - (avg by(instance, job) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100))
                * on(instance) group_left(nodename)
                topk by (instance) (1, node_uname_info)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 3m
        keep_firing_for: 0s
        annotations:
          summary: CPU usage is above 80%
        isPaused: false
        notification_settings:
          receiver: Discord

      - uid: cfuljip1bk0sgb
        title: Memory high usage
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: >-
                ((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100)
                * on(instance) group_left(nodename)
                topk by (instance) (1, node_uname_info)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [90]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 3m
        keep_firing_for: 2m
        annotations:
          summary: Memory usage is above 90%
        isPaused: false
        notification_settings:
          receiver: Discord

      - uid: ffuljm34zdi4gc
        title: Disk high usage
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: >-
                ((1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100)
                * on(instance) group_left(nodename)
                topk by (instance) (1, node_uname_info)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [85]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 3m
        keep_firing_for: 2m
        annotations:
          summary: Disk usage is above 85%
        isPaused: false
        notification_settings:
          receiver: Discord

      - uid: cfuro34dc8934b
        title: Resend Webhook down
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: up{job="resend-webhook", instance="resend-webhook:3001"}
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 3m
        keep_firing_for: 2m
        annotations:
          summary: Webhook down
        isPaused: false
        notification_settings:
          receiver: Discord

      - uid: cfuljm3router1
        title: User Service down
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: up{job="user_service", instance="user_service:9102"}
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 3m
        keep_firing_for: 2m
        annotations:
          summary: User service is down
        isPaused: false
        notification_settings:
          receiver: Discord

      - uid: cfuljm3router2
        title: Router high error rate
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: (sum(rate(router_errors_total[5m])) / sum(rate(router_requests_total[5m]))) * 100
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [10]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: ["C"]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 5m
        keep_firing_for: 2m
        annotations:
          summary: Router error rate is above 10%
        isPaused: false
        notification_settings:
          receiver: Discord